### PR TITLE
Visual Studio 2015 support.

### PR DESCRIPTION
**Pull request by dsaltares**
Adds Visual Studio 2015 solution and LvEdRenderingEngine project.
Solves issue #26.

### CODE REVIEW

**Comment by saltares** [comment]
After 0036871b6b1b79638f31203c60b2e8691fd5bd4f, this is the last thing needed to fully support VS2015.

**Comment by saltares** [comment]
@abeckus is this good to merge?

**Comment by abeckus** [comment]
Hi David,
Thanks for the effort, but unfortunately I can't just do a simple merge, because our main repo is hosted in company's SVN that has  different folder structures and project references.
So basically I make changes in our trunk and push them to GitHub using  a custom tool that fixes up all the inconsistencies.  
Ideally we should make GitHub our main repo and let everyone use it.
Another approach is to write another custom tool to reverse the process (take changes from GitHub repo and apply them to our trunk.
At this time ATF and LevelEditor are in maintenance mode. I will fix critical bugs reported by GitHub users but add new features only when requested by our internal customers.
Btw, can you tell me a bit your LevelEditor project. 
What features stand out and what are the challenges (artichtectureal issues etc.)
your feedback will help me to improve LevelEditor (whenever I get a chance to work on it).

Thanks
Alan

**Comment by saltares** [comment]
Hi @abeckus,

I understand, although it's a shame, because a project with this potential and quality could really benefit from community support. I'm not saying merge everything, but only what you guys really think could make LevelEditor better.

So, I'm part of the [LibGDX](https://github.com/libgdx/libgdx) team and was just experimenting with LevelEditor for a side project of mine using said framework. Nothing too serious yet.

I simply had Visual Studio 2015 and didn't want to install an older version just for the editor :-D.

**Comment by abeckus** [comment]
Hi David,
I totally agree with you and we will look to ways to improve the workflow.
I finally got a chance to add vs2015 and thanks for posting the pull request. 
currently I am testing vs2015 support in our local branch, the GitHub push will come soon.

Btw, LevelEditor looks much nicer with dark skin theme. I am thinking to make it default.
if you interested to try it out.
Click on View menu and choose Load Skin
from skin load dialog box navigate to this folder: ..\ATF\Framework\Atf.Gui.WinForms\Applications\SkinService\Skins
and open Dark.skn file.


Thanks
Alan

**Comment by dsaltares** [comment]
I don't think this is relevant anymore. Closing.

**Pull request closed without merging**
